'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace DockPanels


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' dockManager control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dockManager As Global.DevExpress.Web.ASPxDocking.ASPxDockManager

		''' <summary>
		''' dckpnl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dckpnl1 As Global.DevExpress.Web.ASPxDocking.ASPxDockPanel

		''' <summary>
		''' CControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CControl1 As Global.DockPanels.CControl

		''' <summary>
		''' dckpnl2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dckpnl2 As Global.DevExpress.Web.ASPxDocking.ASPxDockPanel

		''' <summary>
		''' CControl2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected CControl2 As Global.DockPanels.CControl

		''' <summary>
		''' dckpnl3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dckpnl3 As Global.DevExpress.Web.ASPxDocking.ASPxDockPanel

		''' <summary>
		''' ECControl1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ECControl1 As Global.DockPanels.ECControl

		''' <summary>
		''' dckpnl4 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected dckpnl4 As Global.DevExpress.Web.ASPxDocking.ASPxDockPanel

		''' <summary>
		''' ECControl2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ECControl2 As Global.DockPanels.ECControl

		''' <summary>
		''' zone1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected zone1 As Global.DevExpress.Web.ASPxDocking.ASPxDockZone

		''' <summary>
		''' zone2 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected zone2 As Global.DevExpress.Web.ASPxDocking.ASPxDockZone

		''' <summary>
		''' zone3 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected zone3 As Global.DevExpress.Web.ASPxDocking.ASPxDockZone

		''' <summary>
		''' zone4 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected zone4 As Global.DevExpress.Web.ASPxDocking.ASPxDockZone
	End Class
End Namespace
