'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace DockPanels


	Partial Public Class ECControl

		''' <summary>
		''' btnTime control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected btnTime As Global.DevExpress.Web.ASPxEditors.ASPxButton

		''' <summary>
		''' lblTime control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lblTime As Global.DevExpress.Web.ASPxEditors.ASPxLabel
	End Class
End Namespace
